// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library required_fields;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;



enum Kind {
  None(0),
  Alpha(1),
  Beta(2);

  final int value;
  const Kind(this.value);

  factory Kind.fromValue(int value) {
    switch (value) {
      case 0: return Kind.None;
      case 1: return Kind.Alpha;
      case 2: return Kind.Beta;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static Kind? _createOrNull(int? value) =>
      value == null ? null : Kind.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static const fb.Reader<Kind> reader = _KindReader();
}

class _KindReader extends fb.Reader<Kind> {
  const _KindReader();

  @override
  int get size => 1;

  @override
  Kind read(fb.BufferContext bc, int offset) =>
      Kind.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum VariantTypeId {
  NONE(0),
  UnionMemberA(1),
  UnionMemberB(2);

  final int value;
  const VariantTypeId(this.value);

  factory VariantTypeId.fromValue(int value) {
    switch (value) {
      case 0: return VariantTypeId.NONE;
      case 1: return VariantTypeId.UnionMemberA;
      case 2: return VariantTypeId.UnionMemberB;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static VariantTypeId? _createOrNull(int? value) =>
      value == null ? null : VariantTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static const fb.Reader<VariantTypeId> reader = _VariantTypeIdReader();
}

class _VariantTypeIdReader extends fb.Reader<VariantTypeId> {
  const _VariantTypeIdReader();

  @override
  int get size => 1;

  @override
  VariantTypeId read(fb.BufferContext bc, int offset) =>
      VariantTypeId.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class InlineStruct {
  InlineStruct._(this._bc, this._bcOffset);

  static const fb.Reader<InlineStruct> reader = _InlineStructReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get x => const fb.Float32Reader().read(_bc, _bcOffset + 0);
  double get y => const fb.Float32Reader().read(_bc, _bcOffset + 4);

  @override
  String toString() {
    return 'InlineStruct{x: ${x}, y: ${y}}';
  }

  InlineStructT unpack() => InlineStructT(
      x: x,
      y: y);

  static int pack(fb.Builder fbBuilder, InlineStructT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class InlineStructT implements fb.Packable {
  double x;
  double y;

  InlineStructT({
      required this.x,
      required this.y});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.putFloat32(y);
    fbBuilder.putFloat32(x);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'InlineStructT{x: ${x}, y: ${y}}';
  }
}

class _InlineStructReader extends fb.StructReader<InlineStruct> {
  const _InlineStructReader();

  @override
  int get size => 8;

  @override
  InlineStruct createObject(fb.BufferContext bc, int offset) => 
    InlineStruct._(bc, offset);
}

class InlineStructBuilder {
  InlineStructBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(double x, double y) {
    fbBuilder.putFloat32(y);
    fbBuilder.putFloat32(x);
    return fbBuilder.offset;
  }

}

class InlineStructObjectBuilder extends fb.ObjectBuilder {
  final double _x;
  final double _y;

  InlineStructObjectBuilder({
    required double x,
    required double y,
  })
      : _x = x,
        _y = y;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putFloat32(_y);
    fbBuilder.putFloat32(_x);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class NestedTable {
  NestedTable._(this._bc, this._bcOffset);
  factory NestedTable(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<NestedTable> reader = _NestedTableReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get label => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'NestedTable{label: ${label}}';
  }

  NestedTableT unpack() => NestedTableT(
      label: label);

  static int pack(fb.Builder fbBuilder, NestedTableT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class NestedTableT implements fb.Packable {
  String? label;

  NestedTableT({
      this.label});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? labelOffset = label == null ? null
        : fbBuilder.writeString(label!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, labelOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'NestedTableT{label: ${label}}';
  }
}

class _NestedTableReader extends fb.TableReader<NestedTable> {
  const _NestedTableReader();

  @override
  NestedTable createObject(fb.BufferContext bc, int offset) => 
    NestedTable._(bc, offset);
}

class NestedTableBuilder {
  NestedTableBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addLabelOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class NestedTableObjectBuilder extends fb.ObjectBuilder {
  final String? _label;

  NestedTableObjectBuilder({
    String? label,
  })
      : _label = label;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? labelOffset = _label == null ? null
        : fbBuilder.writeString(_label!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, labelOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class UnionMemberA {
  UnionMemberA._(this._bc, this._bcOffset);
  factory UnionMemberA(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<UnionMemberA> reader = _UnionMemberAReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get a => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 4, 0);

  @override
  String toString() {
    return 'UnionMemberA{a: ${a}}';
  }

  UnionMemberAT unpack() => UnionMemberAT(
      a: a);

  static int pack(fb.Builder fbBuilder, UnionMemberAT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class UnionMemberAT implements fb.Packable {
  int a;

  UnionMemberAT({
      this.a = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addInt32(0, a);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'UnionMemberAT{a: ${a}}';
  }
}

class _UnionMemberAReader extends fb.TableReader<UnionMemberA> {
  const _UnionMemberAReader();

  @override
  UnionMemberA createObject(fb.BufferContext bc, int offset) => 
    UnionMemberA._(bc, offset);
}

class UnionMemberABuilder {
  UnionMemberABuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addA(int? a) {
    fbBuilder.addInt32(0, a);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class UnionMemberAObjectBuilder extends fb.ObjectBuilder {
  final int? _a;

  UnionMemberAObjectBuilder({
    int? a,
  })
      : _a = a;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addInt32(0, _a);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class UnionMemberB {
  UnionMemberB._(this._bc, this._bcOffset);
  factory UnionMemberB(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<UnionMemberB> reader = _UnionMemberBReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get b => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'UnionMemberB{b: ${b}}';
  }

  UnionMemberBT unpack() => UnionMemberBT(
      b: b);

  static int pack(fb.Builder fbBuilder, UnionMemberBT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class UnionMemberBT implements fb.Packable {
  String? b;

  UnionMemberBT({
      this.b});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? bOffset = b == null ? null
        : fbBuilder.writeString(b!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, bOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'UnionMemberBT{b: ${b}}';
  }
}

class _UnionMemberBReader extends fb.TableReader<UnionMemberB> {
  const _UnionMemberBReader();

  @override
  UnionMemberB createObject(fb.BufferContext bc, int offset) => 
    UnionMemberB._(bc, offset);
}

class UnionMemberBBuilder {
  UnionMemberBBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addBOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class UnionMemberBObjectBuilder extends fb.ObjectBuilder {
  final String? _b;

  UnionMemberBObjectBuilder({
    String? b,
  })
      : _b = b;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? bOffset = _b == null ? null
        : fbBuilder.writeString(_b!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, bOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
///  One table with every kind of required non-scalar field.
class AllRequired {
  AllRequired._(this._bc, this._bcOffset);
  factory AllRequired(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<AllRequired> reader = _AllRequiredReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String get reqString => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4)!;
  InlineStruct get reqStruct => InlineStruct.reader.vTableGetNullable(_bc, _bcOffset, 6)!;
  NestedTable get reqTable => NestedTable.reader.vTableGetNullable(_bc, _bcOffset, 8)!;
  VariantTypeId? get reqUnionType => VariantTypeId._createOrNull(const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 10));
  dynamic get reqUnion {
    switch (reqUnionType?.value) {
      case 1: return UnionMemberA.reader.vTableGetNullable(_bc, _bcOffset, 12);
      case 2: return UnionMemberB.reader.vTableGetNullable(_bc, _bcOffset, 12);
      default: return null;
    }
  }
  List<int> get reqInts => const fb.ListReader<int>(fb.Int32Reader()).vTableGetNullable(_bc, _bcOffset, 14)!;
  List<String> get reqStrings => const fb.ListReader<String>(fb.StringReader()).vTableGetNullable(_bc, _bcOffset, 16)!;
  List<NestedTable> get reqTables => const fb.ListReader<NestedTable>(NestedTable.reader).vTableGetNullable(_bc, _bcOffset, 18)!;
  List<Kind> get reqEnums => const fb.ListReader<Kind>(Kind.reader).vTableGetNullable(_bc, _bcOffset, 20)!;

  @override
  String toString() {
    return 'AllRequired{reqString: ${reqString}, reqStruct: ${reqStruct}, reqTable: ${reqTable}, reqUnionType: ${reqUnionType}, reqUnion: ${reqUnion}, reqInts: ${reqInts}, reqStrings: ${reqStrings}, reqTables: ${reqTables}, reqEnums: ${reqEnums}}';
  }

  AllRequiredT unpack() => AllRequiredT(
      reqString: reqString,
      reqStruct: reqStruct.unpack(),
      reqTable: reqTable.unpack(),
      reqUnionType: reqUnionType,
      reqUnion: reqUnion.unpack(),
      reqInts: reqInts.toList(),
      reqStrings: reqStrings.toList(),
      reqTables: reqTables.map((e) => e.unpack()).toList(),
      reqEnums: reqEnums.toList());

  static int pack(fb.Builder fbBuilder, AllRequiredT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

///  One table with every kind of required non-scalar field.
class AllRequiredT implements fb.Packable {
  String reqString;
  InlineStructT reqStruct;
  NestedTableT reqTable;
  VariantTypeId? reqUnionType;
  dynamic reqUnion;
  List<int> reqInts;
  List<String> reqStrings;
  List<NestedTableT> reqTables;
  List<Kind> reqEnums;

  AllRequiredT({
      required this.reqString,
      required this.reqStruct,
      required this.reqTable,
      this.reqUnionType,
      required this.reqUnion,
      required this.reqInts,
      required this.reqStrings,
      required this.reqTables,
      required this.reqEnums});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? reqStringOffset = fbBuilder.writeString(reqString);
    final int? reqTableOffset = reqTable.pack(fbBuilder);
    final int? reqUnionOffset = reqUnion.pack(fbBuilder);
    final int? reqIntsOffset = fbBuilder.writeListInt32(reqInts);
    final int? reqStringsOffset = fbBuilder.writeList(reqStrings.map(fbBuilder.writeString).toList());
    final int? reqTablesOffset = fbBuilder.writeList(reqTables.map((b) => b.pack(fbBuilder)).toList());
    final int? reqEnumsOffset = fbBuilder.writeListInt8(reqEnums.map((f) => f.value).toList());
    fbBuilder.startTable(9);
    fbBuilder.addOffset(0, reqStringOffset);
    fbBuilder.addStruct(1, reqStruct.pack(fbBuilder));
    fbBuilder.addOffset(2, reqTableOffset);
    fbBuilder.addUint8(3, reqUnionType?.value);
    fbBuilder.addOffset(4, reqUnionOffset);
    fbBuilder.addOffset(5, reqIntsOffset);
    fbBuilder.addOffset(6, reqStringsOffset);
    fbBuilder.addOffset(7, reqTablesOffset);
    fbBuilder.addOffset(8, reqEnumsOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'AllRequiredT{reqString: ${reqString}, reqStruct: ${reqStruct}, reqTable: ${reqTable}, reqUnionType: ${reqUnionType}, reqUnion: ${reqUnion}, reqInts: ${reqInts}, reqStrings: ${reqStrings}, reqTables: ${reqTables}, reqEnums: ${reqEnums}}';
  }
}

class _AllRequiredReader extends fb.TableReader<AllRequired> {
  const _AllRequiredReader();

  @override
  AllRequired createObject(fb.BufferContext bc, int offset) => 
    AllRequired._(bc, offset);
}

class AllRequiredBuilder {
  AllRequiredBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(9);
  }

  int addReqStringOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addReqStruct(int offset) {
    fbBuilder.addStruct(1, offset);
    return fbBuilder.offset;
  }
  int addReqTableOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addReqUnionType(VariantTypeId? reqUnionType) {
    fbBuilder.addUint8(3, reqUnionType?.value);
    return fbBuilder.offset;
  }
  int addReqUnionOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addReqIntsOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addReqStringsOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addReqTablesOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addReqEnumsOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }

  int finish() {
    final o = fbBuilder.endTable();
    fbBuilder.required(o, 4);
    fbBuilder.required(o, 6);
    fbBuilder.required(o, 8);
    fbBuilder.required(o, 12);
    fbBuilder.required(o, 14);
    fbBuilder.required(o, 16);
    fbBuilder.required(o, 18);
    fbBuilder.required(o, 20);
    return o;
  }
}

class AllRequiredObjectBuilder extends fb.ObjectBuilder {
  final String _reqString;
  final InlineStructObjectBuilder _reqStruct;
  final NestedTableObjectBuilder _reqTable;
  final VariantTypeId? _reqUnionType;
  final dynamic _reqUnion;
  final List<int> _reqInts;
  final List<String> _reqStrings;
  final List<NestedTableObjectBuilder> _reqTables;
  final List<Kind> _reqEnums;

  AllRequiredObjectBuilder({
    required String reqString,
    required InlineStructObjectBuilder reqStruct,
    required NestedTableObjectBuilder reqTable,
    VariantTypeId? reqUnionType,
    required dynamic reqUnion,
    required List<int> reqInts,
    required List<String> reqStrings,
    required List<NestedTableObjectBuilder> reqTables,
    required List<Kind> reqEnums,
  })
      : _reqString = reqString,
        _reqStruct = reqStruct,
        _reqTable = reqTable,
        _reqUnionType = reqUnionType,
        _reqUnion = reqUnion,
        _reqInts = reqInts,
        _reqStrings = reqStrings,
        _reqTables = reqTables,
        _reqEnums = reqEnums;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? reqStringOffset = fbBuilder.writeString(_reqString);
    final int? reqTableOffset = _reqTable.getOrCreateOffset(fbBuilder);
    final int? reqUnionOffset = _reqUnion.getOrCreateOffset(fbBuilder);
    final int? reqIntsOffset = fbBuilder.writeListInt32(_reqInts);
    final int? reqStringsOffset = fbBuilder.writeList(_reqStrings.map(fbBuilder.writeString).toList());
    final int? reqTablesOffset = fbBuilder.writeList(_reqTables.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? reqEnumsOffset = fbBuilder.writeListInt8(_reqEnums.map((f) => f.value).toList());
    fbBuilder.startTable(9);
    fbBuilder.addOffset(0, reqStringOffset);
    fbBuilder.addStruct(1, _reqStruct.finish(fbBuilder));
    fbBuilder.addOffset(2, reqTableOffset);
    fbBuilder.addUint8(3, _reqUnionType?.value);
    fbBuilder.addOffset(4, reqUnionOffset);
    fbBuilder.addOffset(5, reqIntsOffset);
    fbBuilder.addOffset(6, reqStringsOffset);
    fbBuilder.addOffset(7, reqTablesOffset);
    fbBuilder.addOffset(8, reqEnumsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
