// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library my_game.example;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;


enum TestEnum {
  A(0),
  B(1),
  C(2);

  final int value;
  const TestEnum(this.value);

  factory TestEnum.fromValue(int value) {
    switch (value) {
      case 0: return TestEnum.A;
      case 1: return TestEnum.B;
      case 2: return TestEnum.C;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static TestEnum? _createOrNull(int? value) =>
      value == null ? null : TestEnum.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static const fb.Reader<TestEnum> reader = _TestEnumReader();
}

class _TestEnumReader extends fb.Reader<TestEnum> {
  const _TestEnumReader();

  @override
  int get size => 1;

  @override
  TestEnum read(fb.BufferContext bc, int offset) =>
      TestEnum.fromValue(const fb.Int8Reader().read(bc, offset));
}

class NestedStruct {
  NestedStruct._(this._bc, this._bcOffset);

  static const fb.Reader<NestedStruct> reader = _NestedStructReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<int> get a => const fb.ArrayReader<int>(fb.Int32Reader(), 2).read(_bc, _bcOffset + 0);
  TestEnum get b => TestEnum.fromValue(const fb.Int8Reader().read(_bc, _bcOffset + 8));
  List<TestEnum> get c => const fb.ArrayReader<TestEnum>(TestEnum.reader, 2).read(_bc, _bcOffset + 9);
  List<int> get d => const fb.ArrayReader<int>(fb.Int64Reader(), 2).read(_bc, _bcOffset + 16);

  @override
  String toString() {
    return 'NestedStruct{a: ${a}, b: ${b}, c: ${c}, d: ${d}}';
  }

  NestedStructT unpack() => NestedStructT(
    a: a.toList(growable: false),
    b: b,
    c: c.toList(growable: false),
    d: d.toList(growable: false),
  );

  static int pack(fb.Builder fbBuilder, NestedStructT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class NestedStructT implements fb.Packable {
  List<int> a;
  TestEnum b;
  List<TestEnum> c;
  List<int> d;

  NestedStructT({
    required this.a,
    required this.b,
    required this.c,
    required this.d,
  });

  @override
  int pack(fb.Builder fbBuilder) {
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt64(d[_idx-1]);
    }
    fbBuilder.pad(5);
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt8(c[_idx-1].value);
    }
    fbBuilder.putInt8(b.value);
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt32(a[_idx-1]);
    }
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'NestedStructT{a: ${a}, b: ${b}, c: ${c}, d: ${d}}';
  }
}

class _NestedStructReader extends fb.StructReader<NestedStruct> {
  const _NestedStructReader();

  @override
  int get size => 32;

  @override
  NestedStruct createObject(fb.BufferContext bc, int offset) => 
    NestedStruct._(bc, offset);
}

class NestedStructBuilder {
  NestedStructBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(List<int> a, TestEnum b, List<TestEnum> c, List<int> d) {
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt64(d[_idx-1]);
    }
    fbBuilder.pad(5);
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt8(c[_idx-1].value);
    }
    fbBuilder.putInt8(b.value);
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt32(a[_idx-1]);
    }
    return fbBuilder.offset;
  }

}

class NestedStructObjectBuilder extends fb.ObjectBuilder {
  final List<int> _a;
  final TestEnum _b;
  final List<TestEnum> _c;
  final List<int> _d;

  NestedStructObjectBuilder({
    required List<int> a,
    required TestEnum b,
    required List<TestEnum> c,
    required List<int> d,
  })
      : _a = a,
        _b = b,
        _c = c,
        _d = d;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt64(_d[_idx-1]);
    }
    fbBuilder.pad(5);
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt8(_c[_idx-1].value);
    }
    fbBuilder.putInt8(_b.value);
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt32(_a[_idx-1]);
    }
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class ArrayStruct {
  ArrayStruct._(this._bc, this._bcOffset);

  static const fb.Reader<ArrayStruct> reader = _ArrayStructReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get a => const fb.Float32Reader().read(_bc, _bcOffset + 0);
  List<int> get b => const fb.ArrayReader<int>(fb.Int32Reader(), 15).read(_bc, _bcOffset + 4);
  int get c => const fb.Int8Reader().read(_bc, _bcOffset + 64);
  List<NestedStruct> get d => const fb.ArrayReader<NestedStruct>(NestedStruct.reader, 2).read(_bc, _bcOffset + 72);
  int get e => const fb.Int32Reader().read(_bc, _bcOffset + 136);
  List<int> get f => const fb.ArrayReader<int>(fb.Int64Reader(), 2).read(_bc, _bcOffset + 144);

  @override
  String toString() {
    return 'ArrayStruct{a: ${a}, b: ${b}, c: ${c}, d: ${d}, e: ${e}, f: ${f}}';
  }

  ArrayStructT unpack() => ArrayStructT(
    a: a,
    b: b.toList(growable: false),
    c: c,
    d: d.map((e) => e.unpack()).toList(growable: false),
    e: e,
    f: f.toList(growable: false),
  );

  static int pack(fb.Builder fbBuilder, ArrayStructT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class ArrayStructT implements fb.Packable {
  double a;
  List<int> b;
  int c;
  List<NestedStructT> d;
  int e;
  List<int> f;

  ArrayStructT({
    required this.a,
    required this.b,
    required this.c,
    required this.d,
    required this.e,
    required this.f,
  });

  @override
  int pack(fb.Builder fbBuilder) {
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt64(f[_idx-1]);
    }
    fbBuilder.pad(4);
    fbBuilder.putInt32(e);
    for (int _idx = 2; _idx > 0; --_idx) {
      d[_idx-1].pack(fbBuilder);
    }
    fbBuilder.pad(7);
    fbBuilder.putInt8(c);
    for (int _idx = 15; _idx > 0; --_idx) {
      fbBuilder.putInt32(b[_idx-1]);
    }
    fbBuilder.putFloat32(a);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'ArrayStructT{a: ${a}, b: ${b}, c: ${c}, d: ${d}, e: ${e}, f: ${f}}';
  }
}

class _ArrayStructReader extends fb.StructReader<ArrayStruct> {
  const _ArrayStructReader();

  @override
  int get size => 160;

  @override
  ArrayStruct createObject(fb.BufferContext bc, int offset) => 
    ArrayStruct._(bc, offset);
}

class ArrayStructBuilder {
  ArrayStructBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(double a, List<int> b, int c, List<fb.StructBuilder> d, int e, List<int> f) {
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt64(f[_idx-1]);
    }
    fbBuilder.pad(4);
    fbBuilder.putInt32(e);
    for (int _idx = 2; _idx > 0; --_idx) {
      d[_idx-1]();
    }
    fbBuilder.pad(7);
    fbBuilder.putInt8(c);
    for (int _idx = 15; _idx > 0; --_idx) {
      fbBuilder.putInt32(b[_idx-1]);
    }
    fbBuilder.putFloat32(a);
    return fbBuilder.offset;
  }

}

class ArrayStructObjectBuilder extends fb.ObjectBuilder {
  final double _a;
  final List<int> _b;
  final int _c;
  final List<NestedStructObjectBuilder> _d;
  final int _e;
  final List<int> _f;

  ArrayStructObjectBuilder({
    required double a,
    required List<int> b,
    required int c,
    required List<NestedStructObjectBuilder> d,
    required int e,
    required List<int> f,
  })
      : _a = a,
        _b = b,
        _c = c,
        _d = d,
        _e = e,
        _f = f;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    for (int _idx = 2; _idx > 0; --_idx) {
      fbBuilder.putInt64(_f[_idx-1]);
    }
    fbBuilder.pad(4);
    fbBuilder.putInt32(_e);
    for (int _idx = 2; _idx > 0; --_idx) {
      _d[_idx-1].finish(fbBuilder);
    }
    fbBuilder.pad(7);
    fbBuilder.putInt8(_c);
    for (int _idx = 15; _idx > 0; --_idx) {
      fbBuilder.putInt32(_b[_idx-1]);
    }
    fbBuilder.putFloat32(_a);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class ArrayTable {
  ArrayTable._(this._bc, this._bcOffset);
  factory ArrayTable(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ArrayTable> reader = _ArrayTableReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  ArrayStruct? get a => ArrayStruct.reader.vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'ArrayTable{a: ${a}}';
  }

  ArrayTableT unpack() => ArrayTableT(
    a: a?.unpack(),
  );

  static int pack(fb.Builder fbBuilder, ArrayTableT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class ArrayTableT implements fb.Packable {
  ArrayStructT? a;

  ArrayTableT({
    this.a,
  });

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    if (a != null) {
      fbBuilder.addStruct(0, a!.pack(fbBuilder));
    }
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'ArrayTableT{a: ${a}}';
  }
}

class _ArrayTableReader extends fb.TableReader<ArrayTable> {
  const _ArrayTableReader();

  @override
  ArrayTable createObject(fb.BufferContext bc, int offset) => 
    ArrayTable._(bc, offset);
}

class ArrayTableBuilder {
  ArrayTableBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addA(int offset) {
    fbBuilder.addStruct(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ArrayTableObjectBuilder extends fb.ObjectBuilder {
  final ArrayStructObjectBuilder? _a;

  ArrayTableObjectBuilder({
    ArrayStructObjectBuilder? a,
  })
      : _a = a;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    if (_a != null) {
      fbBuilder.addStruct(0, _a!.finish(fbBuilder));
    }
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

